flink.kafka.brokers.name                =       test
spark.kafka.brokers.name2               =       bigdata
spark.kafka.brokers.name3               =       zms
spark.kafka.brokers.name4               =       zmsNew