# 非必须配置项：spark 任务的appName，不配置则取类名
# spark.appName                    =       test
spark.log.level                    =       INFO

# 关系型数据库连接信息
spark.db.jdbc.url                  =       jdbc:mysql://10.9.15.251:3306/presto_monitor
spark.db.jdbc.driver               =       com.mysql.jdbc.Driver
spark.db.jdbc.user                 =       ztm2
spark.db.jdbc.password             =       ztm2Test$!

# 配置另一个数据源，对应的操作需对应加数字后缀，如：this.spark.jdbcQueryDF2(sql, Seq(1, 2, 3), classOf[Student])
spark.db.jdbc.url2                  =       jdbc:mysql://localhost:3306/spark_common
spark.db.jdbc.driver2               =       com.mysql.jdbc.Driver
spark.db.jdbc.user2                 =       root
spark.db.jdbc.password2             =       root
# 每个批次提交的数据大小，默认1000条
spark.db.jdbc.batch.size2           =       2

spark.db.jdbc.url3                  =       jdbc:postgresql://10.9.30.253:5432/zto_db?networkTimeout=30000&applicationName=YB
spark.db.jdbc.driver3               =       org.postgresql.Driver
spark.db.jdbc.user3                 =       zto_loader
spark.db.jdbc.password3             =       zto_loader
# 事务的隔离级别NONE, READ_COMMITTED, READ_UNCOMMITTED, REPEATABLE_READ, SERIALIZABLE，默认为READ_UNCOMMITTED
spark.db.jdbc.isolation.level3      =       none
# 每个批次插入、更新、删除的数据量，默认为1000
spark.db.jdbc.batch.size3           =       2000