# 非必须配置项：spark 任务的appName，不配置则取类名
# spark.appName                    =       test
spark.log.level                    =       INFO
tableName                          =       spark_test
#tableName                          =       t_hosts

# fire框架埋点日志开关，关闭以后将不再打印埋点日志
spark.fire.log.enable              =       true
# 用于限定fire框架中sql日志的字符串长度
spark.fire.log.sql.length          =       500
#spark.fire.jdbc.storage.level      =       memory_and_disk_ser
# 通过JdbcOper查询后将数据集放到多少个分区中，需根据实际的结果集做配置
#spark.fire.jdbc.query.partitions   =       10

# 关系型数据库连接信息
spark.db.jdbc.url                  =       jdbc:mysql://10.9.15.251:3306/presto_monitor?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
spark.db.jdbc.driver               =       com.mysql.jdbc.Driver
spark.db.jdbc.user                 =       ztm2
spark.db.jdbc.password             =       ztm2Test$!
spark.db.jdbc.batch.size           =       10

# 配置另一个数据源，对应的操作需对应加数字后缀，如：this.spark.jdbcQueryDF2(sql, Seq(1, 2, 3), classOf[Student])
spark.db.jdbc.url2                  =       jdbc:mysql://10.9.15.251:3306/datax?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
spark.db.jdbc.driver2               =       com.mysql.jdbc.Driver
spark.db.jdbc.user2                 =       ztm2
spark.db.jdbc.password2             =       ztm2Test$!
# 每个批次提交的数据大小，默认1000条
spark.db.jdbc.batch.size2           =       2

spark.db.jdbc.url3                  =       jdbc:mysql://192.168.11.140:3306/presto_monitor?useUnicode=true&amp;characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
spark.db.jdbc.driver3               =       com.mysql.jdbc.Driver
spark.db.jdbc.user3                 =       cube
spark.db.jdbc.password3             =       ZTOnVuq#WFDcnSfq11177
# 事务的隔离级别NONE, READ_COMMITTED, READ_UNCOMMITTED, REPEATABLE_READ, SERIALIZABLE，默认为READ_UNCOMMITTED
spark.db.jdbc.isolation.level3      =       none
# 每个批次插入、更新、删除的数据量，默认为1000
spark.db.jdbc.batch.size3           =       2000

spark.db.jdbc.url5                  =       jdbc:mysql://192.168.11.140:3306/presto_monitor?useUnicode=true&amp;characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
spark.db.jdbc.driver5               =       com.mysql.jdbc.Driver
spark.db.jdbc.user5                 =       cube
spark.db.jdbc.password5             =       ZTOnVuq#WFDcnSfq11177
# 事务的隔离级别NONE, READ_COMMITTED, READ_UNCOMMITTED, REPEATABLE_READ, SERIALIZABLE，默认为READ_UNCOMMITTED
spark.db.jdbc.isolation.level5      =       none
# 每个批次插入、更新、删除的数据量，默认为1000
spark.db.jdbc.batch.size5           =       2000