package com.zto.bigdata.spark

object CarbonQL {

  def createStreamingTable = {
    """
      |CREATE TABLE dw_sz_zto_site_senda_bills(
      |	id bigint COMMENT '',
      |	bill_code string COMMENT '单号',
      |	owner_bag_no string COMMENT '包号',
      |	scan_date string COMMENT '寄件时间',
      |	scan_site_id bigint COMMENT '寄件网点id',
      |	customer_stm_fee decimal(10,2) COMMENT '客户系统费用',
      |	customer_bill_fee decimal(10,2) COMMENT '客户面单费',
      |	customer_add_fee decimal(10,2) COMMENT '客户附加费',
      |	area_bill_fee decimal(10,2) COMMENT '承包区面单费',
      |	area_center_fee decimal(10,2) COMMENT '承包区中转费',
      |	area_oper_fee decimal(10,2) COMMENT '承包区操作费',
      |	common_fee decimal(10,2) COMMENT '普通散客费',
      |	avg_weight_fee decimal(10,2) COMMENT '均重费',
      |	add_avg_weight_fee decimal(10,2) COMMENT '均重加收费',
      |	rec_man_id bigint COMMENT '揽件人id',
      |	area_id bigint COMMENT '揽件人归属承包区id',
      |	customer_id bigint COMMENT '面单客户id',
      |	user_prov_customer_id bigint COMMENT '面单发放客户id',
      |	user_prov_customer_name string COMMENT '面单发放客户名称（如果没有客户，那么只存一个名称）',
      |	account_way_id bigint COMMENT '结算id(结算周期表)',
      |	sign_date string COMMENT '签收时间',
      |	sign_site_id bigint COMMENT '签收网点id',
      |	sige_status int COMMENT '0未签收 1已签收',
      |	lock_status int COMMENT '锁定费用0未锁定1锁定',
      |	center_rec_fee decimal(10,2) COMMENT '中心收中转费',
      |	center_rec_count int COMMENT '中心收中费次数',
      |	rec_weight decimal(10,2) COMMENT '收发重量',
      |	center_weight decimal(10,2) COMMENT '中心重量差值，公式为：实际的中心重量减去收件重量',
      |	first_weight_date string COMMENT '第一次称重时间',
      |	account_weight decimal(10,2) COMMENT '结算重量',
      |	dispatch string COMMENT '目的地',
      |	dispatch_id bigint COMMENT '目的地ID',
      |	disp_date string COMMENT '派件时间',
      |	disp_site_id bigint COMMENT '派件网点id',
      |	disp_weight decimal(10,2) COMMENT '派件重量',
      |	other_date string COMMENT '问题件时间',
      |	center_send_date string COMMENT '中心发件时间',
      |	center_scan_man_code string COMMENT '中心扫描员code',
      |	center_site_id bigint COMMENT '中心扫描网点id',
      |	man_fee decimal(10,2) COMMENT '业务员提成',
      |	disp_fee decimal(10,2) COMMENT '有偿派费',
      |	add_disp_fee decimal(10,2) COMMENT '续重派费',
      |	surface_fee decimal(10,2) COMMENT '面单成本',
      |	gross_fee decimal(10,2) COMMENT '毛利',
      |	goods_payment decimal(10,2) COMMENT '到付款',
      |	di_fee decimal(10,2) COMMENT '到付手续费',
      |	cod_payment decimal(10,2) COMMENT '代收货款',
      |	cod_fee decimal(10,2) COMMENT '代收手续费',
      |	type int COMMENT '寄件单类型0散客1客户2承包区4业务员',
      |	bill_status int COMMENT '0未计算1待计算2已计算3待核销4已核销 弃用待核销状态',
      |	class_type int COMMENT '运输方式 1是汽运 2是航空',
      |	goods_type int COMMENT '1是物品2是文件',
      |	bill_type int COMMENT '面单类型0线上1普通',
      |	return_status int COMMENT '退件状态0否1是',
      |	date_source int COMMENT '数据来源1收2发3到',
      |	gmt_modifie string COMMENT '修改时间',
      |	editor_name string COMMENT '修改人',
      |	avg_status int COMMENT '是否计算均重费0否1是',
      |	gmt_create string COMMENT '入库时间',
      |	proceeds_man string COMMENT '收款人',
      |	proceeds_time string COMMENT '收款时间',
      |	hexiao_man string COMMENT '核销人',
      |	hexiao_time string COMMENT '核销时间',
      |	hexiao_fee decimal(10,2) COMMENT '首次核销的金额，以后不会再修改',
      |	remark string COMMENT '备注',
      |	account_user_id bigint COMMENT '结算用户',
      |	lock_account_user int COMMENT '1是锁定 0未锁定',
      |	extend1 string COMMENT '扩展字段',
      |	extend2 string COMMENT '扩展字段',
      |	gmt_modified string COMMENT '修改时间',
      |	city_id bigint COMMENT '',
      |	lock_man string COMMENT '锁定或解锁人',
      |	lock_time string COMMENT '锁定或解锁时间',
      |	dispatch_type int COMMENT '目的地来源0未知1订单2建包发3中心发',
      |	order_type int COMMENT '订单来源0散单1线上2线下',
      |	two_level_fee decimal(10,2) COMMENT '二级中转费',
      |	bill_subsidy decimal(10,2) COMMENT '面单补贴',
      |	bill_date string COMMENT '账单日期',
      |	bill_user_site_id bigint COMMENT '面单使用网点',
      |	bill_provide_diff int COMMENT '1面单使用和账单网点不一致',
      |	user_provide_customer_type int COMMENT '2是业务员类型',
      |	user_data_source int COMMENT '1是掌中通',
      |	order_code string COMMENT '订单编码',
      |	partner_trade_id string COMMENT '合作商交易流水号')
      |STORED BY 'carbondata'
      |TBLPROPERTIES('streaming'='true')
    """.stripMargin
  }
}
