flink.hive.cluster                  =       test
flink.kafka.brokers.name            =       test
# 必须配置项：kafka的topic列表，以逗号分隔
flink.kafka.topics                  =       flink
flink.kafka.group.id                =       fire
flink.kafka.enable.auto.commit      =       true
flink.fire.rest.filter.enable       =       false

# 关系型数据库连接信息
flink.db.jdbc.url                  =       jdbc:mysql://10.9.15.251:3306/presto_monitor?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
flink.db.jdbc.driver               =       com.mysql.jdbc.Driver
flink.db.jdbc.user                 =       ztm2
flink.db.jdbc.password             =       ztm2Test$!
flink.db.jdbc.batch.size           =       3
flink.fire.sink.jdbc.default.flushInterval      =       30000
flink.db.jdbc.max.retry            =       5

# 关系型数据库连接信息
flink.db.jdbc.url3                  =       jdbc:mysql://10.9.15.251:3306/datax?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
flink.db.jdbc.driver3               =       com.mysql.jdbc.Driver
flink.db.jdbc.user3                 =       ztm2
flink.db.jdbc.password3             =       ztm2Test$!
flink.db.jdbc.batch.size3           =       3