flink.kafka.brokers.name            =       zms
# 必须配置项：kafka的topic列表，以逗号分隔
flink.kafka.topics                  =       aries_binlog_preorder
flink.kafka.group.id                =       fire
flink.fire.rest.filter.enable       =       false
flink.hive.cluster                  =       batch
flink.stream.checkpoint.interval    =       30000