flink.kafka.brokers.name            =       test
# 必须配置项：kafka的topic列表，以逗号分隔
flink.kafka.topics                  =       flink
flink.kafka.group.id                =       fire
flink.kafka.enable.auto.commit      =       true
spark.fire.rest.filter.enable       =       false
flink.stream.time.characteristic    =       EventTime
flink.default.parallelism           =       2
flink.hive.cluster                  =       J:\\flink\\