#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# ----------------------------------------------- < \u96C6\u7FA4  \u914D\u7F6E > ------------------------------------------------ #
# flink\u672C\u5730\u72B6\u6001\u8DEF\u5F84\u9009\u4E3E\u6240\u4F9D\u8D56\u7684zk\u5730\u5740
state.external.zookeeper.url                                                        =       10.4.139.57:2181

# ----------------------------------------------- < kafka \u914D\u7F6E > ----------------------------------------------- #
# kafka\u96C6\u7FA4\u540D\u79F0\u4E0E\u96C6\u7FA4\u5730\u5740\u6620\u5C04\uFF1Akafka.brokers.name=bigdata | kafka.brokers.name=zms
fire.kafka.cluster.map.bigdata                                                      =       192.168.25.80:9092,192.168.25.81:9092,192.168.25.82:9092,192.168.25.129:9092,192.168.25.130:9092,192.168.25.131:9092
fire.kafka.cluster.map.zms                                                          =       192.168.11.101:9092,192.168.11.102:9092,192.168.11.103:9092,192.168.1.173:9092,192.168.5.29:9092,192.168.5.30:9092
fire.kafka.cluster.map.zmsNew                                                       =       192.168.73.31:9092,192.168.73.32:9092,192.168.73.33:9092,192.168.73.34:9092,192.168.73.35:9092,192.168.73.36:9092
fire.kafka.cluster.map.test                                                         =       10.7.68.185:9092,10.7.68.186:9092,10.7.68.188:9092
fire.kafka.cluster.map.bigdata_test                                                 =       kafka-server:9092

fire.kafka.cluster.map.NEW_BIGDATA_CLUSTER                                          =       newbigdatab1.ztosys.com:9092,newbigdatab2.ztosys.com:9092,newbigdatab3.ztosys.com:9092
fire.kafka.cluster.map.ZmsKafka_Aries                                               =       zmskafkaariesb1.ztosys.com:9092,zmskafkaariesb2.ztosys.com:9092,zmskafkaariesb3.ztosys.com:9092
fire.kafka.cluster.map.oggKafka                                                     =       oggkafkab1.ztosys.com:9092,oggkafkab2.ztosys.com:9092,oggkafkab3.ztosys.com:9092
fire.kafka.cluster.map.ZmsKafka04                                                   =       kafka04b1.ztosys.com:9092,kafka04b2.ztosys.com:9092,kafka04b3.ztosys.com:9092
fire.kafka.cluster.map.ZmsHzdxKafka_bigdata                                         =       zmshzdxkafkabigdatab1.ztosys.com:9092,zmshzdxkafkabigdatab2.ztosys.com:9092,zmshzdxkafkabigdatab3.ztosys.com:9092
fire.kafka.cluster.map.NEW-Logkafka                                                 =       newlogkafkab1.ztosys.com:9092,newlogkafkab2.ztosys.com:9092,newlogkafkab3.ztosys.com:9092
fire.kafka.cluster.map.ZmsHzdxkafka02                                               =       zmshzdxkafka02b1.ztosys.com:9092,zmshzdxkafka02b2.ztosys.com:9092,zmshzdxkafka02b3.ztosys.com:9092

# --------------------------------------------- < RocketMQ \u914D\u7F6E > ---------------------------------------------- #
fire.rocket.cluster.map.ZmsHzdxClusterA                                             =       zmshzdxclusterans1.ztosys.com:9876;zmshzdxclusterans2.ztosys.com:9876;zmshzdxclusterans3.ztosys.com:9876;zmshzdxclusterans4.ztosys.com:9876
fire.rocket.cluster.map.ZmsClusterX                                                 =       zmsclusterxns1.ztosys.com:9876;zmsclusterxns2.ztosys.com:9876
fire.rocket.cluster.map.ZmsClusterB                                                 =       zmsclusterbns1.ztosys.com:9876;zmsclusterbns2.ztosys.com:9876
fire.rocket.cluster.map.MEW-CANAL-CLUSTER                                           =       newcanalclusterns1.ztosys.com:9876;newcanalclusterns2.ztosys.com:9876
fire.rocket.cluster.map.Zms-Spark-Cluster                                           =       mqsparkclusterns1.ztosys.com:9876;mqsparkclusterns2.ztosys.com:9876
fire.rocket.cluster.map.ZmsClusterA                                                 =       zmsclusterans1.ztosys.com:9876;zmsclusterans2.ztosys.com:9876
fire.rocket.cluster.map.bigdata_test                                                =       rocketmq-server:9876

# -------------------------------------------- < spark-hive \u914D\u7F6E > --------------------------------------------- #
# \u79BB\u7EBF\u96C6\u7FA4hive metastore\u5730\u5740\uFF08\u522B\u540D\uFF1Abatch\uFF09
fire.hive.cluster.map.batch                                                         =       thrift://hzpl004138023-hadoop-zh.ztosys.com:9083,thrift://hzpl004138024-hadoop-zh.ztosys.com:9083,thrift://hzpl004138041-hadoop-zh.ztosys.com:9083,thrift://hzpl004138042-hadoop-zh.ztosys.com:9083,thrift://hzpl004138051-hadoop-zh.ztosys.com:9083
fire.hive.cluster.map.batch_new                                                     =       thrift://hzpl004138023-hadoop-zh.ztosys.com:9083,thrift://hzpl004138024-hadoop-zh.ztosys.com:9083,thrift://hzpl004138041-hadoop-zh.ztosys.com:9083,thrift://hzpl004138042-hadoop-zh.ztosys.com:9083,thrift://hzpl004138051-hadoop-zh.ztosys.com:9083
# \u5B9E\u65F6\u96C6\u7FA4hive metastore\u5730\u5740\uFF08\u522B\u540D\uFF1Astreaming\uFF09
fire.hive.cluster.map.streaming                                                     =       thrift://192.168.25.180:9083
# \u6D4B\u8BD5\u96C6\u7FA4hive metastore\u5730\u5740\uFF08\u522B\u540D\uFF1Atest\uFF09
fire.hive.cluster.map.test                                                          =       thrift://10.9.46.107:9083

# -------------------------------------------- < flink-hive \u914D\u7F6E > --------------------------------------------- #
# \u79BB\u7EBF\u96C6\u7FA4hive-site.xml\u5B58\u653E\u8DEF\u5F84\uFF08\u522B\u540D\uFF1Abatch\uFF09
flink.fire.hive.site.path.map.batch                                                 =       /opt/apache/flink/conf/hive/batch
# \u5B9E\u65F6\u96C6\u7FA4hive-site.xml\u5B58\u653E\u8DEF\u5F84\uFF08\u522B\u540D\uFF1Astreaming\uFF09
flink.fire.hive.site.path.map.streaming                                             =       /opt/apache/flink/conf/hive/streaming
# \u6D4B\u8BD5\u96C6\u7FA4hive-site.xml\u5B58\u653E\u8DEF\u5F84\uFF08\u522B\u540D\uFF1Atest\uFF09
flink.fire.hive.site.path.map.test                                                  =       /home/hadoop/flink/conf/

# ----------------------------------------------- < HDFS \u914D\u7F6E > ------------------------------------------------ #
# \u7528\u4E8E\u662F\u5426\u542F\u7528HDFS HA
hdfs.ha.enable                                                                      =       true
# \u79BB\u7EBFhive\u96C6\u7FA4\u7684HDFS HA\u914D\u7F6E\u9879\uFF0C\u89C4\u5219\u4E3A\u7EDF\u4E00\u7684ha\u524D\u7F00\uFF1Aspark.hdfs.ha.conf.+hive.cluster\u540D\u79F0+hdfs\u4E13\u95E8\u7684ha\u914D\u7F6E
hdfs.ha.conf.batch.fs.defaultFS                                                     =       hdfs://nameservice1
hdfs.ha.conf.batch.dfs.nameservices                                                 =       nameservice1
hdfs.ha.conf.batch.dfs.ha.namenodes.nameservice1                                    =       namenode5231,namenode5229
hdfs.ha.conf.batch.dfs.namenode.rpc-address.nameservice1.namenode5231               =       hzpl004133168-hadoop-zh.ztosys.com:8020
hdfs.ha.conf.batch.dfs.namenode.rpc-address.nameservice1.namenode5229               =       hzpl004132188-hadoop-zh.ztosys.com:8020
hdfs.ha.conf.batch.dfs.client.failover.proxy.provider.nameservice1                  =       org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider

hdfs.ha.conf.batch_new.fs.defaultFS                                                 =       hdfs://nameservice1
hdfs.ha.conf.batch_new.dfs.nameservices                                             =       nameservice1
hdfs.ha.conf.batch_new.dfs.ha.namenodes.nameservice1                                =       namenode5231,namenode5229
hdfs.ha.conf.batch_new.dfs.namenode.rpc-address.nameservice1.namenode5231           =       hzpl004133168-hadoop-zh.ztosys.com:8020
hdfs.ha.conf.batch_new.dfs.namenode.rpc-address.nameservice1.namenode5229           =       hzpl004132188-hadoop-zh.ztosys.com:8020
hdfs.ha.conf.batch_new.dfs.client.failover.proxy.provider.nameservice1              =       org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider

# \u5B9E\u65F6hive\u96C6\u7FA4\u7684HDFS HA\u914D\u7F6E\u9879\uFF0C\u89C4\u5219\u4E3A\u7EDF\u4E00\u7684ha\u524D\u7F00\uFF1Aspark.hdfs.ha.conf.+hive.cluster\u540D\u79F0+hdfs\u4E13\u95E8\u7684ha\u914D\u7F6E
hdfs.ha.conf.streaming.fs.defaultFS                                                 =       hdfs://appcluster
hdfs.ha.conf.streaming.dfs.nameservices                                             =       appcluster
hdfs.ha.conf.streaming.dfs.ha.namenodes.appcluster                                  =       nn1,nn2
hdfs.ha.conf.streaming.dfs.namenode.rpc-address.appcluster.nn1                      =       HZPL025180:8020
hdfs.ha.conf.streaming.dfs.namenode.rpc-address.appcluster.nn2                      =       HZPL025181:8020
hdfs.ha.conf.streaming.dfs.client.failover.proxy.provider.appcluster                =       org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider

# \u6D4B\u8BD5\u73AF\u5883hadoop HA\u914D\u7F6E
hdfs.ha.conf.test.fs.defaultFS                                                      =       hdfs://ns1
hdfs.ha.conf.test.dfs.nameservices                                                  =       ns1
hdfs.ha.conf.test.dfs.ha.namenodes.ns1                                              =       namenode310,namenode318
hdfs.ha.conf.test.dfs.namenode.rpc-address.ns1.namenode310                          =       SHTL009046107:8020
hdfs.ha.conf.test.dfs.namenode.rpc-address.ns1.namenode318                          =       SHTL009046109:8020
hdfs.ha.conf.test.dfs.client.failover.proxy.provider.ns1                            =       org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider

# ----------------------------------------------- < HBase \u914D\u7F6E > ----------------------------------------------- #
# \u8001\u96C6\u7FA4hbase\u7684zk\u5730\u5740\uFF08\u522B\u540D\uFF1Aold\uFF09
fire.hbase.cluster.map.old                                                          =       hadoop10.zto:2181,hadoop11.zto:2181,hadoop12.zto:2181
# \u79BB\u7EBF\u96C6\u7FA4hbase\u7684zk\u5730\u5740\uFF08\u522B\u540D\uFF1Abatch\uFF09
fire.hbase.cluster.map.batch                                                        =       HZPL025041:2181,HZPL025040:2181,HZPL025042:2181,HZPL025039:2181,HZPL025038:2181
# \u5B9E\u65F6\u96C6\u7FA4hbase\u7684zk\u5730\u5740\uFF08\u522B\u540D\uFF1Astreaming\uFF09
fire.hbase.cluster.map.streaming                                                    =       hzpl004129059-hbase-dc.ztosys.com:2181,hzpl004129062-hbase-dc.ztosys.com:2181,hzpl004129066-hbase-dc.ztosys.com:2181,hzpl004129069-hbase-dc.ztosys.com:2181,hzpl004129076-hbase-dc.ztosys.com:2181
# \u6D4B\u8BD5\u96C6\u7FA4hbase\u7684zk\u5730\u5740\uFF08\u522B\u540D\uFF1Atest\uFF09
fire.hbase.cluster.map.test                                                         =       SHTL009046110:2181,SHTL009046111:2181,SHTL009046109:2181

# --------------------------------------------- <  \u914D\u7F6E\u4E2D\u5FC3\u914D\u7F6E  > --------------------------------------------- #
# \u914D\u7F6E\u4E2D\u5FC3\u63A5\u53E3\u8C03\u7528\u79D8\u94A5
fire.config_center.register.conf.secret                                             =      21fa30b7f2082b1b12dfbc7c8c6d70b9
# \u914D\u7F6E\u4E2D\u5FC3\u6CE8\u518C\u4E0E\u914D\u7F6E\u63A5\u53E3\u751F\u4EA7\u5730\u5740
fire.config_center.register.conf.prod.address                                       =      http://192.168.33.199:8080/zrcToExternal/zrcConfCallBackNew
# \u914D\u7F6E\u4E2D\u5FC3\u6CE8\u518C\u4E0E\u914D\u7F6E\u63A5\u53E3\u6D4B\u8BD5\u5730\u5740
fire.config_center.register.conf.test.address                                       =      http://10.9.38.156:8080/zrcToExternal/zrcConfCallBackNew

# arthas tunnel \u670D\u52A1\u7684ws\u5730\u5740
fire.analysis.arthas.tunnel_server.url                                              =      ws://10.4.128.26:7777/ws