#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# ----------------------------------------------- < 集群  配置 > ------------------------------------------------ #
# flink本地状态路径选举所依赖的zk地址
state.external.zookeeper.url                                                        =       10.4.139.57:2181

# ----------------------------------------------- < kafka 配置 > ----------------------------------------------- #
# kafka集群名称与集群地址映射：kafka.brokers.name=bigdata | kafka.brokers.name=zms
fire.kafka.cluster.map.bigdata                                                      =       192.168.25.80:9092,192.168.25.81:9092,192.168.25.82:9092,192.168.25.129:9092,192.168.25.130:9092,192.168.25.131:9092
fire.kafka.cluster.map.zms                                                          =       192.168.11.101:9092,192.168.11.102:9092,192.168.11.103:9092,192.168.1.173:9092,192.168.5.29:9092,192.168.5.30:9092
fire.kafka.cluster.map.zmsNew                                                       =       192.168.73.31:9092,192.168.73.32:9092,192.168.73.33:9092,192.168.73.34:9092,192.168.73.35:9092,192.168.73.36:9092
fire.kafka.cluster.map.test                                                         =       10.7.68.185:9092,10.7.68.186:9092,10.7.68.188:9092
fire.kafka.cluster.map.bigdata_test                                                 =       10.9.46.111:9092

fire.kafka.cluster.map.NEW_BIGDATA_CLUSTER                                          =       newbigdatab1.ztosys.com:9092,newbigdatab2.ztosys.com:9092,newbigdatab3.ztosys.com:9092
fire.kafka.cluster.map.ZmsKafka_Aries                                               =       zmskafkaariesb1.ztosys.com:9092,zmskafkaariesb2.ztosys.com:9092,zmskafkaariesb3.ztosys.com:9092
fire.kafka.cluster.map.oggKafka                                                     =       oggkafkab1.ztosys.com:9092,oggkafkab2.ztosys.com:9092,oggkafkab3.ztosys.com:9092
fire.kafka.cluster.map.ZmsKafka04                                                   =       kafka04b1.ztosys.com:9092,kafka04b2.ztosys.com:9092,kafka04b3.ztosys.com:9092
fire.kafka.cluster.map.ZmsHzdxKafka_bigdata                                         =       zmshzdxkafkabigdatab1.ztosys.com:9092,zmshzdxkafkabigdatab2.ztosys.com:9092,zmshzdxkafkabigdatab3.ztosys.com:9092
fire.kafka.cluster.map.NEW-Logkafka                                                 =       newlogkafkab1.ztosys.com:9092,newlogkafkab2.ztosys.com:9092,newlogkafkab3.ztosys.com:9092
fire.kafka.cluster.map.ZmsHzdxkafka02                                               =       zmshzdxkafka02b1.ztosys.com:9092,zmshzdxkafka02b2.ztosys.com:9092,zmshzdxkafka02b3.ztosys.com:9092

# --------------------------------------------- < RocketMQ 配置 > ---------------------------------------------- #
fire.rocket.cluster.map.ZmsHzdxClusterA                                             =       zmshzdxclusterans1.ztosys.com:9876;zmshzdxclusterans2.ztosys.com:9876;zmshzdxclusterans3.ztosys.com:9876;zmshzdxclusterans4.ztosys.com:9876
fire.rocket.cluster.map.ZmsClusterX                                                 =       zmsclusterxns1.ztosys.com:9876;zmsclusterxns2.ztosys.com:9876
fire.rocket.cluster.map.ZmsClusterB                                                 =       zmsclusterbns1.ztosys.com:9876;zmsclusterbns2.ztosys.com:9876
fire.rocket.cluster.map.MEW-CANAL-CLUSTER                                           =       newcanalclusterns1.ztosys.com:9876;newcanalclusterns2.ztosys.com:9876
fire.rocket.cluster.map.Zms-Spark-Cluster                                           =       mqsparkclusterns1.ztosys.com:9876;mqsparkclusterns2.ztosys.com:9876
fire.rocket.cluster.map.ZmsClusterA                                                 =       zmsclusterans1.ztosys.com:9876;zmsclusterans2.ztosys.com:9876
fire.rocket.cluster.map.bigdata_test                                                =       10.9.46.112:9876

# -------------------------------------------- < spark-hive 配置 > --------------------------------------------- #
# 离线集群hive metastore地址（别名：batch）
fire.hive.cluster.map.batch                                                         =       thrift://hzpl004138023-hadoop-zh.ztosys.com:9083,thrift://hzpl004138024-hadoop-zh.ztosys.com:9083,thrift://hzpl004138041-hadoop-zh.ztosys.com:9083,thrift://hzpl004138042-hadoop-zh.ztosys.com:9083,thrift://hzpl004138051-hadoop-zh.ztosys.com:9083
fire.hive.cluster.map.batch_new                                                     =       thrift://hzpl004138023-hadoop-zh.ztosys.com:9083,thrift://hzpl004138024-hadoop-zh.ztosys.com:9083,thrift://hzpl004138041-hadoop-zh.ztosys.com:9083,thrift://hzpl004138042-hadoop-zh.ztosys.com:9083,thrift://hzpl004138051-hadoop-zh.ztosys.com:9083
# 实时集群hive metastore地址（别名：streaming）
fire.hive.cluster.map.streaming                                                     =       thrift://192.168.25.180:9083
# 测试集群hive metastore地址（别名：test）
fire.hive.cluster.map.test                                                          =       thrift://10.9.46.107:9083

# -------------------------------------------- < flink-hive 配置 > --------------------------------------------- #
# 离线集群hive-site.xml存放路径（别名：batch）
flink.fire.hive.site.path.map.batch                                                 =       /opt/apache/flink/conf/hive/batch
# 实时集群hive-site.xml存放路径（别名：streaming）
flink.fire.hive.site.path.map.streaming                                             =       /opt/apache/flink/conf/hive/streaming
# 测试集群hive-site.xml存放路径（别名：test）
flink.fire.hive.site.path.map.test                                                  =       /home/hadoop/flink/conf/

# ----------------------------------------------- < HDFS 配置 > ------------------------------------------------ #
# 用于是否启用HDFS HA
hdfs.ha.enable                                                                      =       true
# 离线hive集群的HDFS HA配置项，规则为统一的ha前缀：spark.hdfs.ha.conf.+hive.cluster名称+hdfs专门的ha配置
hdfs.ha.conf.batch.fs.defaultFS                                                     =       hdfs://nameservice1
hdfs.ha.conf.batch.dfs.nameservices                                                 =       nameservice1
hdfs.ha.conf.batch.dfs.ha.namenodes.nameservice1                                    =       namenode5231,namenode5229
hdfs.ha.conf.batch.dfs.namenode.rpc-address.nameservice1.namenode5231               =       hzpl004133168-hadoop-zh.ztosys.com:8020
hdfs.ha.conf.batch.dfs.namenode.rpc-address.nameservice1.namenode5229               =       hzpl004132188-hadoop-zh.ztosys.com:8020
hdfs.ha.conf.batch.dfs.client.failover.proxy.provider.nameservice1                  =       org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider

hdfs.ha.conf.batch_new.fs.defaultFS                                                 =       hdfs://nameservice1
hdfs.ha.conf.batch_new.dfs.nameservices                                             =       nameservice1
hdfs.ha.conf.batch_new.dfs.ha.namenodes.nameservice1                                =       namenode5231,namenode5229
hdfs.ha.conf.batch_new.dfs.namenode.rpc-address.nameservice1.namenode5231           =       hzpl004133168-hadoop-zh.ztosys.com:8020
hdfs.ha.conf.batch_new.dfs.namenode.rpc-address.nameservice1.namenode5229           =       hzpl004132188-hadoop-zh.ztosys.com:8020
hdfs.ha.conf.batch_new.dfs.client.failover.proxy.provider.nameservice1              =       org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider

# 实时hive集群的HDFS HA配置项，规则为统一的ha前缀：spark.hdfs.ha.conf.+hive.cluster名称+hdfs专门的ha配置
hdfs.ha.conf.streaming.fs.defaultFS                                                 =       hdfs://appcluster
hdfs.ha.conf.streaming.dfs.nameservices                                             =       appcluster
hdfs.ha.conf.streaming.dfs.ha.namenodes.appcluster                                  =       nn1,nn2
hdfs.ha.conf.streaming.dfs.namenode.rpc-address.appcluster.nn1                      =       HZPL025180:8020
hdfs.ha.conf.streaming.dfs.namenode.rpc-address.appcluster.nn2                      =       HZPL025181:8020
hdfs.ha.conf.streaming.dfs.client.failover.proxy.provider.appcluster                =       org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider

# 测试环境hadoop HA配置
hdfs.ha.conf.test.fs.defaultFS                                                      =       hdfs://ns1
hdfs.ha.conf.test.dfs.nameservices                                                  =       ns1
hdfs.ha.conf.test.dfs.ha.namenodes.ns1                                              =       namenode310,namenode318
hdfs.ha.conf.test.dfs.namenode.rpc-address.ns1.namenode310                          =       SHTL009046107:8020
hdfs.ha.conf.test.dfs.namenode.rpc-address.ns1.namenode318                          =       SHTL009046109:8020
hdfs.ha.conf.test.dfs.client.failover.proxy.provider.ns1                            =       org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider

# ----------------------------------------------- < HBase 配置 > ----------------------------------------------- #
# 老集群hbase的zk地址（别名：old）
fire.hbase.cluster.map.old                                                          =       hadoop10.zto:2181,hadoop11.zto:2181,hadoop12.zto:2181
# 离线集群hbase的zk地址（别名：batch）
fire.hbase.cluster.map.batch                                                        =       HZPL025041:2181,HZPL025040:2181,HZPL025042:2181,HZPL025039:2181,HZPL025038:2181
# 实时集群hbase的zk地址（别名：streaming）
fire.hbase.cluster.map.streaming                                                    =       hzpl004129059-hbase-dc.ztosys.com:2181,hzpl004129062-hbase-dc.ztosys.com:2181,hzpl004129066-hbase-dc.ztosys.com:2181,hzpl004129069-hbase-dc.ztosys.com:2181,hzpl004129076-hbase-dc.ztosys.com:2181
# 测试集群hbase的zk地址（别名：test）
fire.hbase.cluster.map.test                                                         =       SHTL009046110:2181,SHTL009046111:2181,SHTL009046109:2181

# --------------------------------------------- <  配置中心配置  > --------------------------------------------- #
# 配置中心接口调用秘钥
fire.config_center.register.conf.secret                                             =      21fa30b7f2082b1b12dfbc7c8c6d70b9
# 配置中心注册与配置接口生产地址
fire.config_center.register.conf.prod.address                                       =      http://192.168.33.199:8080/zrcToExternal/zrcConfCallBackNew
# 配置中心注册与配置接口测试地址
fire.config_center.register.conf.test.address                                       =      http://10.9.38.156:8080/zrcToExternal/zrcConfCallBackNew

# arthas tunnel 服务的ws地址
fire.analysis.arthas.tunnel_server.url                                              =      ws://10.7.69.32:7777/ws