#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


# checkpoint相关配置
# checkpoint频率，-1表示关闭
flink.stream.checkpoint.interval                                                    =      -1
# EXACTLY_ONCE/AT_LEAST_ONCE
flink.stream.checkpoint.mode                                                        =      EXACTLY_ONCE
# checkpoint超时时间，单位：毫秒
flink.stream.checkpoint.timeout                                                     =      600000
# 同时checkpoint操作的并发数
flink.stream.checkpoint.max.concurrent                                              =      1
# 两次checkpoint的最小停顿时间
flink.stream.checkpoint.min.pause.between                                           =      -1
# 如果有更近的checkpoint时，是否将作业回退到该检查点
flink.stream.checkpoint.prefer.recovery                                             =      false
# 可容忍checkpoint失败的次数，默认不允许失败
flink.stream.checkpoint.tolerable.failure.number                                    =      0
# 当cancel job时保留checkpoint
flink.stream.checkpoint.externalized                                                =      RETAIN_ON_CANCELLATION
# 是否开启非对齐的checkpoint
flink.stream.checkpoint.unaligned.enable                                            =      false
# 运行模式：STREAMING/BATCH/AUTOMATIC
# flink.runtime.mode                                                                =      STREAMING
# 指定消费rocketmq的起始消费位点
flink.rocket.starting.offsets                                                       =      latest