# 非必须配置项：spark 任务的appName，不配置则取类名
# spark.appName                    =       test
spark.log.level                    =       INFO
# 非必须配置项：默认是大数据的kafka地址，如果连zms，则将bigdata替换为zms
spark.kafka.brokers.name           =       zmsNew
# 必须配置项：kafka的topic列表，以逗号分隔
spark.kafka.topics                 =       sjzn_spark_order_unique_topic
# 非必须配置项：默认为appName
spark.kafka.group.id               =       fire
spark.streaming.batch.duration     =       30
# 仅用于本地测试，线上任务请移除该配置
spark.io.compression.codec          =       snappy

# ------------------- < hbase 配置 > ------------------- #
# 用于区分不同的hbase集群: batch/streaming/old
spark.hbase.cluster                =       streaming
spark.fire.rest.filter.enable      =       true

# spark的参数可以直接写在下面，都会被加载，覆盖程序中默认的配置信息
spark.speculation                  =       false
spark.streaming.concurrentJobs     =       1