# spark 任务的appName，不配置则取类名
spark.appName                      =       hiveReader
spark.log.level                    =       ERROR
# ------------------- < hive 配置 > ------------------- #
# hive 集群名称（batch离线hive/streaming 180集群hive/test本地测试hive），用于spark跨集群读取hive元数据信息
spark.hive.cluster                 =       thrift://hzpl025056:9083
# 仅用于本地测试，线上任务请移除该配置
spark.io.compression.codec         =       snappy