spark.fire.task.schedule.enable         =       true
# 定时任务黑名单，配置方法名，多个以逗号分隔，配置的方法将不再被定时任务定时拉起
spark.fire.scheduler.blacklist          =       jvmMonitor,setConf2,registerAcc

# 仅用于本地测试，线上任务请移除该配置
spark.io.compression.codec          =       snappy