spark.fire.rest.filter.enable       =       false
spark.hbase.cluster                 =       test
spark.fire.scheduler.blacklist      =       jvmMonitor,setConf2,registerAcc
spark.hive.cluster                  =       test
spark.kafka.brokers.name            =       10.7.68.185:9092,10.7.68.186:9092,10.7.68.188:9092
spark.kafka.starting.offsets        =       earliest
spark.kafka.topics                  =       aries_binlog_preorder
spark.kafka.group.id                =       flink
spark.kafka.max.partition.fetch.bytes=      10000000
spark.kafka.log.level               =       error
spark.log.level.fire_conf.com.zto.fire.common.db    =   warn