# 仅用于本地测试，线上任务请移除该配置
spark.io.compression.codec          =       snappy
spark.fire.rest.filter.enable       =       false
spark.hbase.cluster                 =       batch
spark.fire.scheduler.blacklist      =       jvmMonitor,setConf2,registerAcc
spark.hive.cluster                  =       test
spark.kafka.brokers.name            =       test
spark.kafka.topics                  =       flink
spark.kafka.group.id                =       flink
spark.kafka.max.partition.fetch.bytes=      10000000