spark.hive.cluster=test
spark.hbase.cluster=test
# 非必须配置项：默认是大数据的kafka地址
spark.kafka.brokers.name=zms
spark.kafka.topics=aries_binlog_preorder
spark.kafka.group.id=fire2
spark.fire.rest.filter.enable=false
spark.fire.streaming.remember=10000
spark.fire.zrc.enable=false
spark.fire.rest.enable=true
spark.fire.task.schedule.enable=false