
#########################################################################################
#  JDBC数据源配置信息详见：common.properties，公共数据源配置可放到common.properties中，便于维护    #
#########################################################################################


# 非必须配置项：spark 任务的appName，不配置则取类名
# spark.appName                    =       test
tableName                          =       spark_test
#tableName                          =       t_hosts

spark.log.level                     =       INFO
spark.fire.jdbc.storage.level       =       DISK_ONLY
spark.fire.jdbc.query.partitions    =       12
spark.fire.acc.enable               =       true
spark.log.level.fire_conf.com.zto.fire=     info
# fire框架埋点日志开关，关闭以后将不再打印埋点日志
spark.fire.log.enable               =       true
# 用于限定fire框架中sql日志的字符串长度
spark.fire.log.sql.length           =       100
#spark.fire.jdbc.storage.level      =       memory_and_disk_ser
# 通过JdbcConnector查询后将数据集放到多少个分区中，需根据实际的结果集做配置
#spark.fire.jdbc.query.partitions   =       10
spark.fire.rest.filter.enable       =       false

hello.world                         =       2020
spark.fire.config_center.enable     =       true
hello.world.flag                    =       false
hello.world.flag2                   =       false