
#########################################################################################
#  JDBC数据源配置信息详见：common.properties，公共数据源配置可放到common.properties中，便于维护    #
#########################################################################################


# 非必须配置项：spark 任务的appName，不配置则取类名
# spark.appName                    =       test
spark.log.level                    =       INFO
# 非必须配置项：默认是大数据的kafka地址，如果连zms，则将bigdata替换为zms
spark.kafka.brokers.name           =       zmsNew
# 必须配置项：kafka的topic列表，以逗号分隔
spark.kafka.topics                 =       sjzn_spark_order_unique_topic
# 非必须配置项：默认为appName
spark.kafka.group.id               =       fire
spark.fire.rest.filter.enable      =       false