# 非必须配置项：spark 任务的appName，不配置则取类名
spark.appName                      =       HBaseHadoopTest
spark.log.level                    =       ERROR
# ------------------- < hbase 配置 > ------------------- #
# 用于区分不同的hbase集群: batch/streaming/old
spark.hbase.cluster                =       batch
# 通过HBase scan后repartition的分区数，需根据scan后的数据量做配置
spark.fire.hbase.scan.partitions   =       3
spark.fire.hbase.storage.level     =       DISK_ONLY