# 定义url的别名与url对应关系，后续可通过别名进行配置
flink.db.jdbc.url.map.test         =       jdbc:mysql://10.9.46.116:3306/fire

# 支持别名或直接指定url
flink.db.jdbc.url                  =       test
flink.db.jdbc.driver               =       com.mysql.jdbc.Driver
flink.db.jdbc.user                 =       root
flink.db.jdbc.password             =       ..root726

flink.db.jdbc.url2                  =       jdbc:mysql://10.9.46.116:3306/fire2
flink.db.jdbc.driver2               =       com.mysql.jdbc.Driver
flink.db.jdbc.user2                 =       root
flink.db.jdbc.password2             =       ..root726

flink.db.jdbc.url6                  =       jdbc:mysql://10.9.46.116:3306/fire6
flink.db.jdbc.driver6               =       com.mysql.jdbc.Driver
flink.db.jdbc.user6                 =       root
flink.db.jdbc.password6             =       ..root726

flink.db.jdbc.url7                  =       jdbc:mysql://10.9.46.116:3306/fire7
flink.db.jdbc.driver7               =       com.mysql.jdbc.Driver
flink.db.jdbc.user7                 =       root
flink.db.jdbc.password7             =       ..root726

flink.db.jdbc.url8                  =       jdbc:mysql://10.9.46.116:3306/fire8
flink.db.jdbc.driver8               =       com.mysql.jdbc.Driver
flink.db.jdbc.user8                 =       root
flink.db.jdbc.password8             =       ..root726