# 定义url的别名与url对应关系，后续可通过别名进行配置
flink.db.jdbc.url.map.test         =       jdbc:mysql://10.9.46.116:3306/fire
# 支持别名或直接指定url
flink.db.jdbc.url                  =       test
flink.db.jdbc.driver               =       com.mysql.jdbc.Driver
flink.db.jdbc.user                 =       root
flink.db.jdbc.password             =       ..root726
flink.db.jdbc.batch.size           =       10

flink.db.jdbc.url2                  =       jdbc:mysql://10.9.15.251:3306/datax?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&useSSL=false
flink.db.jdbc.driver2               =       com.mysql.jdbc.Driver
flink.db.jdbc.user2                 =       datax_rw
flink.db.jdbc.password2             =       datax_rw123$Z
# 每个批次提交的数据大小，默认1000条
flink.db.jdbc.batch.size2           =       2

flink.db.jdbc.url3                  =       jdbc:mysql://192.168.11.140:3306/presto_monitor?useUnicode=true&amp;characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&autoReconnect=true&useSSL=false
flink.db.jdbc.driver3               =       com.mysql.jdbc.Driver
flink.db.jdbc.user3                 =       cube
flink.db.jdbc.password3             =       ZTOnVuq#WFDcnSfq11177
flink.db.jdbc.isolation.level3      =       none
# 每个批次插入、更新、删除的数据量，默认为1000
flink.db.jdbc.batch.size3           =       2000

flink.db.jdbc.url5                  =       jdbc:mysql://192.168.11.140:3306/presto_monitor?useUnicode=true&amp;characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&autoReconnect=true&useSSL=false
flink.db.jdbc.driver5               =       com.mysql.jdbc.Driver
flink.db.jdbc.user5                 =       cube
flink.db.jdbc.password5             =       ZTOnVuq#WFDcnSfq11177
flink.db.jdbc.isolation.level5      =       none
# 每个批次插入、更新、删除的数据量，默认为1000
flink.db.jdbc.batch.size5           =       2000

flink.db.jdbc.url6                  =       jdbc:mysql://10.9.46.116:3306/fire6
flink.db.jdbc.driver6               =       com.mysql.jdbc.Driver
flink.db.jdbc.user6                 =       root
flink.db.jdbc.password6             =       ..root726

# 支持别名或直接指定url
flink.db.jdbc.url7                  =       jdbc:mysql://10.9.46.116:3306/fire7
flink.db.jdbc.driver7               =       com.mysql.jdbc.Driver
flink.db.jdbc.user7                 =       root
flink.db.jdbc.password7             =       ..root726

# 支持别名或直接指定url
flink.db.jdbc.url8                  =       jdbc:mysql://10.9.46.116:3306/fire8
flink.db.jdbc.driver8               =       com.mysql.jdbc.Driver
flink.db.jdbc.user8                 =       root
flink.db.jdbc.password8             =       ..root726