#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# 定义url的别名与url对应关系，后续可通过别名进行配置
flink.db.jdbc.url.map.test         =       jdbc:mysql://10.9.46.116:3306/fire

# 支持别名或直接指定url
flink.db.jdbc.url                  =       test
flink.db.jdbc.driver               =       com.mysql.jdbc.Driver
flink.db.jdbc.user                 =       root
flink.db.jdbc.password             =       ..root726

flink.db.jdbc.url2                  =       jdbc:mysql://10.9.46.116:3306/fire2
flink.db.jdbc.driver2               =       com.mysql.jdbc.Driver
flink.db.jdbc.user2                 =       root
flink.db.jdbc.password2             =       ..root726

flink.db.jdbc.url6                  =       jdbc:mysql://10.9.46.116:3306/fire6
flink.db.jdbc.driver6               =       com.mysql.jdbc.Driver
flink.db.jdbc.user6                 =       root
flink.db.jdbc.password6             =       ..root726

flink.db.jdbc.url7                  =       jdbc:mysql://10.9.46.116:3306/fire7
flink.db.jdbc.driver7               =       com.mysql.jdbc.Driver
flink.db.jdbc.user7                 =       root
flink.db.jdbc.password7             =       ..root726

flink.db.jdbc.url8                  =       jdbc:mysql://10.9.46.116:3306/fire8
flink.db.jdbc.driver8               =       com.mysql.jdbc.Driver
flink.db.jdbc.user8                 =       root
flink.db.jdbc.password8             =       ..root726
fire.rest.filter.enable             =       false
fire.rest.url.show.enable           =       true