flink.kafka.brokers.name=192.168.50.123:9092,192.168.50.124:9092,192.168.50.125:9092,192.168.50.126:9092,192.168.50.127:9092
flink.kafka.topics=sjzn_spark_binlog_order_topic
flink.kafka.group.id=kafka_demo_flink_002
flink.fire.rest.filter.enable=false
flink.hbase.max.retry=2
flink.stream.time.characteristic=ProcessingTime
#flink.checkpoint.interval=30000
akka.ask.timeout=30000
web.timeout=30000
#spark.fire.zrc.enable=false
#spark.fire.rest.enable=false