# config
app.id=fire

dev.meta=http://apollo.meta.dev.ztosys.com
fat.meta=http://apollo.meta.test.ztosys.com
uat.meta=http://192.168.54.12:8080
pro.meta=http://apollo-meta-pro.ztosys.com
sit.meta=http://apollo.meta.sit.ztosys.com

