# 非必须配置项：spark 任务的appName，不配置则取类名
spark.appName                      =       HBaseConnectorTest
spark.log.level                    =       warn
# ------------------- < hbase 配置 > ------------------- #
# 用于区分不同的hbase集群: batch/streaming/old
spark.hbase.cluster                =       test
spark.hbase.cluster2               =       test
spark.fire.hbase.scan.repartitions =       3
spark.fire.hbase.storage.level     =       DISK_ONLY
fire.shutdown.auto.exit            =       true