package com.zto.fire.flink.core.util

import com.google.common.collect.HashBasedTable
import com.zto.fire.common.anno.FieldName
import com.zto.fire.common.util.{GlobalConstants, ValueUtils}
import com.zto.fire.flink.core.bean.FlinkTableSchema
import org.apache.commons.lang3.StringUtils
import org.apache.flink.api.common.ExecutionConfig.ClosureCleanerLevel
import org.apache.flink.api.common.{ExecutionConfig, ExecutionMode, InputDependencyConstraint}
import org.apache.flink.types.Row

/**
 * flink相关工具类
 *
 * @author ChengLong 2020年1月16日 16:28:23
 * @since 0.4.1
 */
object FlinkUtils {
  // 维护schema、fieldName与fieldIndex关系
  private[this] val schemaTable = HashBasedTable.create[FlinkTableSchema, String, Int]

  /**
   * 将schema、fieldName与fieldIndex信息维护到table中
   */
  private[this] def extendSchemaTable(schema: FlinkTableSchema): Unit = {
    if (ValueUtils.isNotEmpty(schema) && !schemaTable.containsRow(schema)) {
      for (i <- 0 until schema.getFieldCount) {
        schemaTable.put(schema, schema.getFieldName(i).get(), i)
      }
    }
  }

  /**
   * 将Row转为自定义bean，以JavaBean中的Field为基准
   * bean中的field名称要与DataFrame中的field名称保持一致
   *
   * @return
   */
  def flinkRowToBean[T](schema: FlinkTableSchema, row: Row, clazz: Class[T]): T = {
    val obj = clazz.newInstance()
    if (row != null && clazz != null) {
      try {
        this.extendSchemaTable(schema)
        clazz.getDeclaredFields.foreach(field => {
          field.setAccessible(true)
          val anno = field.getAnnotation(classOf[FieldName])
          val begin = if (anno == null) true else !anno.disuse()
          if (begin) {
            val fieldName = if (anno != null && ValueUtils.isNotEmpty(anno.value())) anno.value().trim else field.getName
            if (this.schemaTable.contains(schema, fieldName)) {
              val fieldIndex = this.schemaTable.get(schema, fieldName)
              field.set(obj, row.getField(fieldIndex))
            }
          }
        })
      } catch {
        case e: Exception => e.printStackTrace()
      }
    }
    obj
  }

  /**
   * 解析并设置配置文件中的配置信息
   */
  def parseConf(config: ExecutionConfig): ExecutionConfig = {
    ValueUtils.requireNonNullForce(config, "Flink配置实例不能为空")

    // flink.auto.generate.uid.enable=true 默认为：true
    if (GlobalConstants.FlinkConf.autoGenerateUidEnable) {
      config.enableAutoGeneratedUIDs()
    } else {
      config.disableAutoGeneratedUIDs()
    }

    // flink.auto.type.registration.enable=true 默认为：true
    if (!GlobalConstants.FlinkConf.autoTypeRegistrationEnable) {
      config.disableAutoTypeRegistration()
    }

    // flink.force.avro.enable=true  默认值为：false
    if (GlobalConstants.FlinkConf.forceAvroEnable) {
      config.enableForceAvro()
    } else {
      config.disableForceAvro()
    }

    // flink.force.kryo.enable=true 默认值为：false
    if (GlobalConstants.FlinkConf.forceKryoEnable) {
      config.enableForceKryo()
    } else {
      config.disableForceKryo()
    }

    // flink.generic.types.enable=true  默认值为：false
    if (GlobalConstants.FlinkConf.genericTypesEnable) {
      config.enableGenericTypes()
    } else {
      config.disableGenericTypes()
    }

    // flink.object.reuse.enable=true 默认值为：false
    if (GlobalConstants.FlinkConf.objectReuseEnable) {
      config.enableObjectReuse()
    } else {
      config.disableObjectReuse()
    }

    // flink.auto.watermark.interval=0  默认值为：0
    if (GlobalConstants.FlinkConf.autoWatermarkInterval != -1) config.setAutoWatermarkInterval(GlobalConstants.FlinkConf.autoWatermarkInterval)

    // flink.closure.cleaner.level=recursive  默认值为：RECURSIVE，包括：RECURSIVE、NONE、TOP_LEVEL
    if (StringUtils.isNotBlank(GlobalConstants.FlinkConf.closureCleanerLevel)) config.setClosureCleanerLevel(ClosureCleanerLevel.valueOf(GlobalConstants.FlinkConf.closureCleanerLevel.toUpperCase))

    // flink.default.input.dependency.constraint=any  默认值：ANY，包括：ANY、ALL
    if (StringUtils.isNotBlank(GlobalConstants.FlinkConf.defaultInputDependencyConstraint)) config.setDefaultInputDependencyConstraint(InputDependencyConstraint.valueOf(GlobalConstants.FlinkConf.defaultInputDependencyConstraint.toUpperCase))

    // flink.execution.mode=pipelined 默认值：PIPELINED，包括：PIPELINED、PIPELINED_FORCED、BATCH、BATCH_FORCED
    if (StringUtils.isNotBlank(GlobalConstants.FlinkConf.executionMode)) config.setExecutionMode(ExecutionMode.valueOf(GlobalConstants.FlinkConf.executionMode.toUpperCase))

    // flink.latency.tracking.interval=0  默认值：0
    if (GlobalConstants.FlinkConf.latencyTrackingInterval != -1) config.setLatencyTrackingInterval(GlobalConstants.FlinkConf.latencyTrackingInterval)

    // flink.max.parallelism=1  没有默认值
    if (GlobalConstants.FlinkConf.maxParallelism != -1) config.setMaxParallelism(GlobalConstants.FlinkConf.maxParallelism)

    // flink.task.cancellation.interval=1 无默认值
    if (GlobalConstants.FlinkConf.taskCancellationInterval != -1) config.setTaskCancellationInterval(GlobalConstants.FlinkConf.taskCancellationInterval)

    // flink.task.cancellation.timeout.millis=1000  无默认值
    if (GlobalConstants.FlinkConf.taskCancellationTimeoutMillis != -1) config.setTaskCancellationTimeout(GlobalConstants.FlinkConf.taskCancellationTimeoutMillis)

    // flink.use.snapshot.compression=false 默认值：false
    config.setUseSnapshotCompression(GlobalConstants.FlinkConf.useSnapshotCompression)

    config
  }
}
