#flink.hive.cluster                  =       test
flink.kafka.brokers.name            =       bigdata_test
# 必须配置项：kafka的topic列表，以逗号分隔
flink.kafka.topics                  =       fire
flink.kafka.group.id                =       fire
flink.fire.rest.filter.enable       =       false
flink.fire.config_center.enable     =       true
flink.fire.rest.url.show.enable     =       true
# 关系型数据库连接信息
flink.db.jdbc.url                  =       jdbc:clickhouse://10.9.46.116:8123/fire
flink.db.jdbc.driver               =       ru.yandex.clickhouse.ClickHouseDriver
flink.db.jdbc.user                 =       default
flink.db.jdbc.password             =       default