flink.hive.cluster                  =       J:\\flink\\
flink.kafka.brokers.name            =       test
# 必须配置项：kafka的topic列表，以逗号分隔
flink.kafka.topics                  =       flink
flink.kafka.group.id                =       fire
flink.kafka.enable.auto.commit      =       true
flink.fire.rest.filter.enable       =       false
flink.default.parallelism           =       8
flink.max.parallelism               =       8

# 关系型数据库连接信息（jdbc信息统一配置在common.properties中）