flink.hive.cluster                  =       test
flink.kafka.brokers.name            =       bigdata_test
# 必须配置项：kafka的topic列表，以逗号分隔
flink.kafka.topics                  =       fire
flink.kafka.group.id                =       fire
flink.kafka.enable.auto.commit      =       true
flink.fire.rest.filter.enable       =       false

# 关系型数据库连接信息
flink.hbase.max.retry               =       2
flink.hbase.cluster                 =       test
flink.stream.checkpoint.interval    =       30000