flink.kafka.brokers.name            =       bigdata_test
# 必须配置项：kafka的topic列表，以逗号分隔
flink.kafka.topics                  =       fire
flink.kafka.group.id                =       fire
flink.kafka.enable.auto.commit      =       true
flink.hbase.cluster                 =       test
flink.log.level.fire_conf.com.zto.fire.common.db    =   warn
flink.log.level.fire_conf.org.apache.kafka    =   error
flink.max.parallelism                       =   8