flink.kafka.brokers.name            =       10.9.46.111:9092
# 必须配置项：kafka的topic列表，以逗号分隔
flink.kafka.topics                  =       fire
flink.kafka.group.id                =       fire
spark.fire.rest.filter.enable       =       false
flink.hive.cluster                  =       batch
flink.stream.checkpoint.interval    =       10000
flink.hive.support.enable                       =       true