flink.kafka.brokers.name            =       10.9.45.97:9092,10.9.15.38:9092,10.9.36.49:9092,10.9.36.50:9092
# 必须配置项：kafka的topic列表，以逗号分隔
flink.kafka.topics                  =       flink
flink.kafka.group.id                =       fire
flink.kafka.enable.auto.commit      =       true
flink.hive.cluster                  =       test
flink.hbase.cluster                 =       test
flink.log.level.fire_conf.com.zto.fire.common.db    =   warn
flink.log.level.fire_conf.org.apache.kafka    =   error
flink.max.parallelism                       =   2