
#########################################################################################
#  JDBC数据源配置信息详见：common.properties，公共数据源配置可放到common.properties中，便于维护    #
#########################################################################################


#flink.hive.cluster                  =       test
flink.kafka.brokers.name            =       bigdata_test
# 必须配置项：kafka的topic列表，以逗号分隔
flink.kafka.topics                  =       fire
flink.kafka.group.id                =       fire
flink.fire.rest.filter.enable       =       false
flink.fire.config_center.enable     =       true
flink.fire.rest.url.show.enable     =       true

# flink所支持的参数
state.checkpoints.num-retained      =       3
state.backend.incremental           =       true
state.backend.rocksdb.files.open    =       5000

hello.world                         =       2020
hello.world.flag                    =       false
hello.world.flag2                   =       false