#flink.hive.cluster                  =       test
flink.kafka.brokers.name            =       bigdata_test
# 必须配置项：kafka的topic列表，以逗号分隔
flink.kafka.topics                  =       fire
flink.kafka.group.id                =       fire
flink.fire.rest.filter.enable       =       false
flink.fire.config_center.enable     =       true
flink.fire.rest.url.show.enable     =       true
# 关系型数据库连接信息
# systemctl start mariadb.service
flink.db.jdbc.url                  =       jdbc:mysql://10.9.46.116:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&useSSL=false
flink.db.jdbc.driver               =       com.mysql.jdbc.Driver
flink.db.jdbc.user                 =       root
flink.db.jdbc.password             =       @_@root726$$
flink.db.jdbc.batch.size           =       10

# 关系型数据库连接信息
flink.db.jdbc.url3                  =       jdbc:mysql://10.9.15.251:3306/datax?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
flink.db.jdbc.driver3               =       com.mysql.jdbc.Driver
flink.db.jdbc.user3                 =       datax_rw
flink.db.jdbc.password3             =       datax_rw123$Z
flink.db.jdbc.batch.size3           =       3
flink.stream.checkpoint.interval    =       1000

# flink所支持的参数
state.checkpoints.num-retained      =       3
state.backend.incremental           =       true
state.backend.rocksdb.files.open    =       5000