flink.kafka.brokers.name            =       bigdata_test
# 必须配置项：kafka的topic列表，以逗号分隔
flink.kafka.topics                  =       fire
flink.kafka.group.id                =       fire
flink.kafka.enable.auto.commit      =       true
flink.fire.rest.filter.enable       =       false
flink.default.parallelism           =       2
flink.stream.checkpoint.interval    =       10000