# 非必须配置项：spark 任务的appName，不配置则取类名
# spark.appName                    =       test
spark.log.level                    =       INFO
# 非必须配置项：默认是大数据的kafka地址，如果连zms，则将bigdata替换为zms
spark.kafka.brokers.name           =       bigdata
# 必须配置项：kafka的topic列表，以逗号分隔
spark.kafka.topics                 =       aries_binlog_order
# 非必须配置项：默认为appName
spark.kafka.group.id               =       fire
spark.streaming.batch.duration     =       60

# ------------------- < hbase 配置 > ------------------- #
# 用于区分不同的hbase集群: batch/streaming/old
spark.hbase.cluster                =       streaming

# spark的参数可以直接写在下面，都会被加载，覆盖程序中默认的配置信息
spark.speculation                  =       false
spark.streaming.concurrentJobs     =       1