spark.kafka.brokers.name           =       zmsNew
# 必须配置项：kafka的topic列表，以逗号分隔
spark.kafka.group.id               =       fire
spark.kafka.topics                 =       sjzn_spark_scan_send_topic
spark.hive.cluster                 =       streaming
spark.kafka.poll.timeout.ms        =       10000

# 仅用于本地测试，线上任务请移除该配置
spark.io.compression.codec          =       snappy