# 仅用于本地测试，线上任务请移除该配置
spark.io.compression.codec          =       snappy
flink.kafka.brokers.name            =       test
# 必须配置项：kafka的topic列表，以逗号分隔
flink.kafka.topics                  =       flink
flink.kafka.group.id                =       fire
flink.kafka.enable.auto.commit      =       true
spark.fire.rest.filter.enable       =       false

spark.hbase.cluster                 =       batch
spark.fire.scheduler.blacklist      =       jvmMonitor,setConf2,registerAcc

spark.impala.jdbc.driver.class.name =       org.apache.hive.jdbc.HiveDriver
spark.impala.daemons.url            =       192.168.25.39,192.168.25.40,192.168.25.41
flink.hive.cluster                  =       J:\\flink\\