# ******************** 配置文件中所指定的信息会覆盖 GlobalConstants.DefaultVals 中的默认值 ******************** #

# 当前common的版本号
common.version                     =       ${project.version}
# ------------------ < spark 配置 > ------------------ #
# spark的应用名称，为空则取类名
spark.appName                      =

spark.chkpoint.dir                 =       hdfs://appcluster/user/spark/ckpoint/

# kafka的groupid，为空则取类名
spark.kafka.group.id               =
# bigdata表示连接大数据的kafka，zms表示连接zms的kafka集群
spark.kafka.brokers.name           =       bigdata
spark.kafka.topics                 =
# 用于配置启动时的消费位点，默认取最新
spark.kafka.starting.offsets       =       latest

# 数据丢失时执行失败
spark.kafka.failOnDataLoss         =       true
spark.kafka.enable.auto.commit     =       false

spark.log.level                    =       WARN
spark.default.database.name        =       tmp
spark.default.table.partition.name =       ds

# ------------------- < hive 配置 > ------------------- #
# hive 集群名称（batch离线hive/streaming 180集群hive/test本地测试hive），用于spark跨集群读取hive元数据信息
hive.cluster                       =       streaming

# ------------------- < hbase 配置 > ------------------- #
# 用于区分不同的hbase集群: batch/streaming/old
hbase.cluster                      =       batch

# ------------------ < impala 配置 > ------------------ #
impala.connection.url              =      jdbc:hive2://192.168.25.37:21050/;auth=noSasl
impala.jdbc.driver.class.name      =      org.apache.hive.jdbc.HiveDriver

# ------------------ < spark 参数 > ------------------- #
spark.streaming.backpressure.enabled=true