spark.fire.config_center.enable                                                     =       false
# 是否关闭fire内置的所有累加器
spark.fire.acc.enable                                                               =       false
spark.ui.killEnabled                                                                =       false
spark.port.maxRetries                                                               =       200
spark.default.parallelism                                                           =       1000
spark.sql.broadcastTimeout                                                          =       3000
spark.ui.timeline.tasks.maximum                                                     =       300
spark.sql.parquet.writeLegacyFormat                                                 =       true
spark.scheduler.listenerbus.eventqueue.size                                         =       130000
spark.serializer                                                                    =       org.apache.spark.serializer.KryoSerializer