spark.port.maxRetries                                                               =       200
spark.ui.killEnabled                                                                =       false
spark.default.parallelism                                                           =       1000
spark.sql.broadcastTimeout                                                          =       3000
spark.ui.timeline.tasks.maximum                                                     =       300
spark.scheduler.listenerbus.eventqueue.size                                         =       130000
spark.serializer                                                                    =       org.apache.spark.serializer.KryoSerializer