flink.log.level=INFO
rocket.cluster.map.ZmsClusterX=localhost:9876
flink.streaming.batch.duration=10
# 非必须配置项：默认是大数据的rocket地址 ZmsClusterX
flink.rocket.brokers.name=192.168.1.174:9876;192.168.1.179:9876
flink.rocket.topics=SCANRECORD
flink.rocket.consumer.instance=FireFramework
#flink.hbase.cluster=streaming
flink.rocket.group.id=sjzn_spark_scanrecord_test
flink.rocket.pull.max.speed.per.partition=15000
flink.rocket.consumer.tag=1||2||3||4||5||8||44||45
flink.streaming.backpressure.enabled=false
flink.streaming.backpressure.initialRate=100