spark.sql.catalog.paimon                =       org.apache.paimon.spark.SparkCatalog
spark.sql.extensions                    =       org.apache.paimon.spark.extensions.PaimonSparkSessionExtensions
spark.sql.catalog.paimon.metastore      =       hive
spark.sql.catalog.paimon.warehouse      =       /user/hive/warehouse