spark.kafka.brokers.name           =       test
# 必须配置项：kafka的topic列表，以逗号分隔
spark.kafka.topics                 =       fire2
# 非必须配置项：默认为appName
spark.kafka.group.id               =       fire
spark.fire.rest.filter.enable      =       false
spark.hive.cluster                 =       test
spark.hbase.cluster                =       test
spark.db.jdbc.url                  =       jdbc:mysql://10.9.15.251:3306/presto_monitor?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
spark.db.jdbc.driver               =       com.mysql.jdbc.Driver
spark.db.jdbc.user                 =       ztm2
spark.db.jdbc.password             =       ztm2Test$!
spark.db.jdbc.batch.size           =       10
spark.chkpoint.dir                 =       /tmp/spark-checkpoint/
spark.sql.shuffle.partitions       =       300
spark.sql.streaming.metricsEnabled =       true