# ******************** 配置文件中所指定的信息会覆盖 GlobalConstants.DefaultVals 中的默认值 ******************** #

# ------------------ < spark 配置 > ------------------ #
test                               =       test
spark.default.table.partition.name =       dt