# ******************** �����ļ�����ָ������Ϣ�Ḳ�� GlobalConstants.DefaultVals �е�Ĭ��ֵ ******************** #

# ------------------ < spark ���� > ------------------ #
spark.runModel                     =       cluster
spark.chkpoint.dir                 =       hdfs://nameservice1/user/spark/ckpoint/
spark.kafka.brokers.name           =       zms
spark.log.level                    =       ERROR
spark.default.database.name        =       tmp
spark.default.table.partition.name =       ds

# ------------------- < hive ���� > ------------------- #
# hive metastore��ַ������spark�缯Ⱥ��ȡhiveԪ������Ϣ
hive.cluster                       =       streaming

# ------------------- < hbase ���� > ------------------- #
# �������ֲ�ͬ��hbase��Ⱥ: batch/streaming/old
hbase.cluster                      =       batch

# ------------------ < impala ���� > ------------------ #
impala.connection.url              =      jdbc:hive2://192.168.25.37:21050/;auth=noSasl
impala.jdbc.driver.class.name      =      org.apache.hive.jdbc.HiveDriver

# ---------------- < carbondata ���� > ---------------- #
carbon.storePath                   =      hdfs://appcluster/user/CarbonStore