# ******************** 配置项中大都有默认值，如有定制化需求，需单独指定，有默认值的配置可不写 ******************** #

# brokers地址，默认192.168.11.101:9092,192.168.11.102:9092,192.168.11.103:9092
spark.kafka.brokers.name           =       zms
# kafka的topic列表，以逗号分隔（无默认值，必须指定）
spark.kafka.topics                 =       thrall2, thrall3, thrall4, thrall5, thrall6, thrall7, thrall8, thrall9
# groupid（可不配置，默认取appName）
spark.kafka.group.id               =       shenzhouSyncStreaming

# 用于配置启动时的消费位点，默认取最新（有默认值latest，可不配置）
spark.kafka.starting.offsets       =       latest
# 数据丢失时执行失败（有默认值true，可不配置）
spark.kafka.failOnDataLoss         =       true
# 是否自动提交offset（有默认值false，可不配置）
spark.kafka.enable.auto.commit     =       false

# ------------------- < hive 配置 > ------------------- #
# hive metastore地址，用于spark跨集群读取hive元数据信息，默认为180hive集群，可不配置
hive.cluster                       =       streaming

# ------------------- < hbase 配置 > ------------------- #
# 用于区分不同的hbase集群: batch/streaming/old，默认为壮汉集群，可不配置
hbase.cluster                      =       batch