# spark 任务的appName，不配置则取类名
spark.appName                      =       hiveReader
spark.log.level                    =       ERROR
# ------------------- < hive 配置 > ------------------- #
# hive 集群名称（batch离线hive/streaming 180集群hive/test本地测试hive），用于spark跨集群读取hive元数据信息
spark.fire.hive.cluster.map.hello  =       thrift://hzpl004138029-hadoop-zh.ztosys.com:9083
spark.hive.cluster                 =       hello