hive.cluster=test
hbase.cluster=test
# 非必须配置项：默认是大数据的kafka地址
kafka.brokers.name=bigdata_test
kafka.topics=fire
kafka.group.id=fire2
fire.rest.filter.enable=true
fire.streaming.remember=10000
fire.rest.enable=true
fire.config_center.local.enable=false
fire.task.schedule.enable=true
local.cores=6
#fire.config_center.enable=false
fire.scheduler.blacklist=jvmMonitor
fire.hello=fire2020

spark.hbase.cluster                =       test
spark.hbase.cluster2                =       test
spark.db.jdbc.url                  =       jdbc:mysql://10.9.15.251:3306/realtime_control?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&useSSL=false
spark.db.jdbc.driver               =       com.mysql.jdbc.Driver
spark.db.jdbc.user                 =       realtime_control_rw
spark.db.jdbc.password             =       realtime_control_rw123$Z
spark.db.jdbc.batch.size           =       10

spark.db.jdbc.url2                  =       jdbc:mysql://10.9.15.251:3306/datax?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&useSSL=false
spark.db.jdbc.driver2               =       com.mysql.jdbc.Driver
spark.db.jdbc.user2                 =       datax_rw
spark.db.jdbc.password2             =       datax_rw123$Z
# 每个批次提交的数据大小，默认1000条
spark.db.jdbc.batch.size2           =       2