spark.tispark.pd.addresses=10.4.131.3:2379,10.4.131.12:2379,10.4.131.204:2379
spark.sql.extensions=org.apache.spark.sql.TiExtensions
spark.redaction.regex=(?i)secret|password
spark.sql.runSQLOnFiles=true
spark.shuffle.service.enabled=false
spark.dynamicAllocation.enabled=false
#spark.hive.cluster                 =       batch
spark.db.jdbc.url                  =       jdbc:clickhouse://192.168.127.160:8123/default
spark.db.jdbc.driver               =       ru.yandex.clickhouse.ClickHouseDriver
spark.db.jdbc.user                 =       default
spark.db.jdbc.password             =       default
spark.db.jdbc.batch.size           =       30000