# ******************** 配置文件中所指定的信息会覆盖  GlobalConstants.DefaultVals 中的默认值 ******************** #

# ----------------------------------------------- < fire 配置 > ------------------------------------------------ #
# 当前fire框架的版本号
spark.fire.version                                                                  =       ${project.version}
# 是否启用restful服务
spark.fire.rest.enable                                                              =       true
# 用于设置是否做接口校验
spark.fire.rest.filter.enable                                                       =       true
# 是否关闭fire内置的所有累加器
spark.fire.acc.enable                                                               =       true
# 日志累加器开关
spark.fire.acc.log.enable                                                           =       true
# 多值累加器开关
spark.fire.acc.multi.counter.enable                                                 =       true
# 多时间维度累加器开关
spark.fire.acc.multi.timer.enable                                                   =       true
# fire框架埋点日志开关，关闭以后将不再打印埋点日志
spark.fire.log.enable                                                               =       true
# 用于限定fire框架中sql日志的字符串长度
spark.fire.log.sql.length                                                           =       100
# fire框架针对jdbc操作后数据集的缓存策略
spark.fire.jdbc.storage.level                                                       =       memory_and_disk_ser
# 通过JdbcOper查询后将数据集放到多少个分区中，需根据实际的结果集做配置
spark.fire.jdbc.query.partitions                                                    =       10
# 是否启用定时调度
spark.fire.task.schedule.enable                                                     =       true
# fire框架rest接口服务最大线程数
spark.fire.restful.max.thread                                                       =       8
# quartz最大线程池大小
spark.fire.quartz.max.thread                                                        =       8
# fire收集日志保留的最多记录数
spark.fire.acc.log.min.size                                                         =       500
# fire收集日志保留的最少记录数
spark.fire.acc.log.max.size                                                         =       1000
# timer累加器保留最大的记录数
spark.fire.acc.timer.max.size                                                       =       1000
# timer累加器清理几小时之前的记录
spark.fire.acc.timer.max.hour                                                       =       12
# env累加器开关
spark.fire.acc.env.enable                                                           =       true
# env累加器保留最多的记录数
spark.fire.acc.env.max.size                                                         =       500
# env累加器保留最少的记录数
spark.fire.acc.env.min.size                                                         =       100
# 定时调度任务黑名单，配置的value为定时任务方法名，多个以逗号分隔
spark.fire.scheduler.blacklist                                                      =
# 是否抛弃zrc独立运行，配置为false表示不向zrc注册，不获取zrc配置
# 注：zrc系统异常时可设置为false，不受zrc影响，可正常发布和运行
spark.fire.zrc.enable                                                               =       true
# 配置打印黑名单，包含该配置将不被打印
spark.fire.conf.print.blacklist                                                     =       .map.,pass,zrc,impala.connection.url,hdfs.ha,print.blacklist
# fire框架restful端口冲突重试次数
spark.fire.restful.port.retry_num                                                   =       3
# fire框架restful端口冲突重试时间（ms）
spark.fire.restful.port.retry_duration                                              =       1000
# 默认的spark日志级别
spark.log.level                                                                     =       WARN
# 日志的级别，统一前缀为：spark.log.level.fire_conf.
spark.log.level.fire_conf.org.apache.spark                                          =       WARN
spark.log.level.fire_conf.org.apache.kafka                                          =       WARN
spark.log.level.fire_conf.com.zto.fire                                              =       INFO
spark.log.level.fire_conf.org.eclipse.jetty.server                                  =       ERROR

# ----------------------------------------------- < spark 配置 > ----------------------------------------------- #
# spark的应用名称，为空则取类名
spark.appName                                                                       =
# spark local模式下使用多少core运行，默认为local[*]，自动根据当前pc的cpu核心数设置
spark.local.cores                                                                   =       *
# spark checkpoint目录地址
spark.chkpoint.dir                                                                  =       hdfs://appcluster/user/spark/ckpoint/
# spark streaming批次时间，可覆盖代码中所指定的时间
spark.streaming.batch.duration                                                      =

# ----------------------------------------------- < kafka 配置 > ----------------------------------------------- #
# kafka的groupid，为空则取类名
spark.kafka.group.id                                                                =
# bigdata表示连接大数据的kafka，zms表示连接zms的kafka集群
# spark.kafka.brokers.name                                                          =       bigdata
# topic列表
spark.kafka.topics                                                                  =
# 用于配置启动时的消费位点，默认取最新
spark.kafka.starting.offsets                                                        =       latest
# 数据丢失时执行失败
spark.kafka.failOnDataLoss                                                          =       true
# 是否启用自动commit
spark.kafka.enable.auto.commit                                                      =       false

# kafka集群名称与集群地址映射：spark.kafka.brokers.name=bigdata | spark.kafka.brokers.name=zms
spark.kafka.cluster.map.bigdata                                                     =       192.168.25.80:9092,192.168.25.81:9092,192.168.25.82:9092,192.168.25.129:9092,192.168.25.130:9092,192.168.25.131:9092
spark.kafka.cluster.map.zms                                                         =       192.168.11.101:9092,192.168.11.102:9092,192.168.11.103:9092,192.168.1.173:9092,192.168.5.29:9092,192.168.5.30:9092
spark.kafka.cluster.map.zmsNew                                                      =       192.168.73.31:9092,192.168.73.32:9092,192.168.73.33:9092,192.168.73.34:9092,192.168.73.35:9092,192.168.73.36:9092
spark.kafka.cluster.map.test                                                        =       10.7.68.185:9092,10.7.68.186:9092,10.7.68.188:9092

# 以spark.kafka.conf开头的配置支持所有kafka client的配置
#spark.kafka.conf.session.timeout.ms                                                =       300000
#spark.kafka.conf.request.timeout.ms                                                =       400000

# --------------------------------------------- < RocketMQ 配置 > ---------------------------------------------- #
spark.rocket.cluster.map.test                                                       =       192.168.1.169:9876;192.168.1.170:9876
# 以spark.rocket.conf开头的配置支持所有rocket client的配置
#spark.rocket.conf.pull.max.speed.per.partition                                     =       5000

# ----------------------------------------------- < HDFS 配置 > ------------------------------------------------ #
# 用于是否启用HDFS HA
spark.hdfs.ha.enable                                                                =       true
# 离线hive集群的HDFS HA配置项，规则为统一的ha前缀：spark.hdfs.ha.conf.+hive.cluster名称+hdfs专门的ha配置
spark.hdfs.ha.conf.batch.fs.defaultFS                                               =       hdfs://nameservice1
spark.hdfs.ha.conf.batch.dfs.nameservices                                           =       nameservice1
spark.hdfs.ha.conf.batch.dfs.ha.namenodes.nameservice1                              =       namenode61,namenode99
spark.hdfs.ha.conf.batch.dfs.namenode.rpc-address.nameservice1.namenode61           =       HZPL025036:8020
spark.hdfs.ha.conf.batch.dfs.namenode.rpc-address.nameservice1.namenode99           =       HZPL025037:8020
spark.hdfs.ha.conf.batch.dfs.client.failover.proxy.provider.nameservice1            =       org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider
# 实时hive集群的HDFS HA配置项，规则为统一的ha前缀：spark.hdfs.ha.conf.+hive.cluster名称+hdfs专门的ha配置
spark.hdfs.ha.conf.streaming.fs.defaultFS                                           =       hdfs://appcluster
spark.hdfs.ha.conf.streaming.dfs.nameservices                                       =       appcluster
spark.hdfs.ha.conf.streaming.dfs.ha.namenodes.appcluster                            =       nn1,nn2
spark.hdfs.ha.conf.streaming.dfs.namenode.rpc-address.appcluster.nn1                =       HZPL025180:8020
spark.hdfs.ha.conf.streaming.dfs.namenode.rpc-address.appcluster.nn2                =       HZPL025181:8020
spark.hdfs.ha.conf.streaming.dfs.client.failover.proxy.provider.appcluster          =       org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider


# ----------------------------------------------- < hive 配置 > ------------------------------------------------ #
# 是否启用hive支持
spark.hive.support.enable                                                           =       true
# hive 集群名称（batch离线hive/streaming 180集群hive/test本地测试hive），用于spark跨集群读取hive元数据信息
spark.hive.cluster                                                                  =
# 默认的hive数据库
spark.default.database.name                                                         =       tmp
# 默认的hive分区字段名称
spark.default.table.partition.name                                                  =       ds
# 离线集群hive metastore地址（别名：batch）
spark.hive.cluster.map.batch                                                        =       thrift://192.168.25.36:9083,thrift://192.168.25.50:9083,thrift://192.168.25.51:9083,thrift://192.168.25.52:9083
# 实时集群hive metastore地址（别名：streaming）
spark.hive.cluster.map.streaming                                                    =       thrift://192.168.25.180:9083
# 测试集群hive metastore地址（别名：test）
spark.hive.cluster.map.test                                                         =       thrift://10.9.46.107:9083
# 离线集群hive-site.xml存放路径（别名：batch）
spark.hive.site.path.map.batch                                                      =       /home/hadoop/flink/conf/hive/batch
# 实时集群hive-site.xml存放路径（别名：streaming）
spark.hive.site.path.map.streaming                                                  =       /home/hadoop/flink/conf/hive/streaming
# 测试集群hive-site.xml存放路径（别名：test）
spark.hive.site.path.map.test                                                       =       /home/hadoop/flink/conf/

# 以spark.hive.conf.为前缀的配置将直接生效，比如开启hive动态分区
# this.spark.sql("set hive.exec.dynamic.partition=true")
#spark.hive.conf.hive.exec.dynamic.partition                                        =       true
# spark.sqlContext.sql("set hive.exec.dynamic.partition.mode=nonstrict")
#spark.hive.conf.hive.exec.dynamic.partition.mode                                   =       nonstrict
#spark.hive.conf.hive.exec.max.dynamic.partitions                                   =       5000


# ----------------------------------------------- < HBase 配置 > ----------------------------------------------- #
# 用于区分不同的hbase集群: batch/streaming/old/test
spark.hbase.cluster                                                                 =
# 一次读写HBase的数据量
spark.hbase.batch.size                                                              =       10000
# fire框架针对hbase操作后数据集的缓存策略
spark.fire.hbase.storage.level                                                      =       memory_and_disk_ser
# 通过HBase scan后repartition的分区数，需根据scan后的数据量做配置
spark.fire.hbase.scan.repartitions                                                  =       1200
# 老集群hbase的zk地址（别名：old）
spark.hbase.cluster.map.old                                                         =       hadoop10.zto:2181,hadoop11.zto:2181,hadoop12.zto:2181
# 离线集群hbase的zk地址（别名：batch）
spark.hbase.cluster.map.batch                                                       =       HZPL025041:2181,HZPL025040:2181,HZPL025042:2181,HZPL025039:2181,HZPL025038:2181
# 实时集群hbase的zk地址（别名：streaming）
spark.hbase.cluster.map.streaming                                                   =       HZPL025024:2181,HZPL025027:2181,HZPL025025:2181,HZPL025023:2181,HZPL025026:2181
# 测试集群hbase的zk地址（别名：test）
spark.hbase.cluster.map.test                                                        =       SHTL009046110:2181,SHTL009046111:2181,SHTL009046109:2181

# hbase connection 配置，约定以：spark.hbase.conf.开头，比如：spark.hbase.conf.hbase.rpc.timeout对应hbase中的配置为hbase.rpc.timeout
spark.hbase.conf.hbase.zookeeper.property.clientPort                                =       2181
spark.hbase.conf.zookeeper.znode.parent                                             =       /hbase
spark.hbase.conf.hbase.rpc.timeout                                                  =       600000
spark.hbase.conf.hbase.snapshot.master.timeoutMillis                                =       600000
spark.hbase.conf.hbase.snapshot.region.timeout                                      =       600000


# ----------------------------------------------- < impala 配置 > ---------------------------------------------- #
spark.impala.connection.url                                                         =      jdbc:hive2://192.168.25.37:21050/;auth=noSasl
spark.impala.jdbc.driver.class.name                                                 =      org.apache.hive.jdbc.HiveDriver

# ----------------------------------------------- < spark 参数 > ----------------------------------------------- #
# Spark相关优化参数列在下面会自动被fire加载生效
spark.streaming.backpressure.enabled                                                =      true

# ----------------------------------------------- <  zrc 配置  > ----------------------------------------------- #
# zrc接口调用秘钥
spark.zrc.register.conf.secret                                                      =      21fa30b7f2082b1b12dfbc7c8c6d70b9
# zrc注册与配置接口生产地址
spark.zrc.register.conf.prod.address                                                =      http://192.168.33.199:8080/zrcToExternal/zrcConfCallBack
# zrc注册与配置接口测试地址
spark.zrc.register.conf.test.address                                                =      http://10.9.38.156:8080/zrcToExternal/zrcConfCallBack
