# ******************** 配置文件中所指定的信息会覆盖  GlobalConstants.DefaultVals 中的默认值 ******************** #

# ----------------------------------------------- < fire  参数 > ----------------------------------------------- #
# 当前common的版本号
spark.fire.version                      =       ${project.version}
# 用于设置是否做接口校验
spark.fire.rest.filter.enable           =       true
# 是否关闭fire内置的所有累加器
spark.fire.acc.enable                   =       true
# 日志累加器开关
spark.fire.acc.log.enable               =       true
# 多值累加器开关
spark.fire.acc.multi.counter.enable     =       true
# 多时间维度累加器开关
spark.fire.acc.multi.timer.enable       =       true
# fire框架埋点日志开关，关闭以后将不再打印埋点日志
spark.fire.log.enable                   =       true
# 用于限定fire框架中sql日志的字符串长度
spark.fire.log.sql.length               =       100
# fire框架针对hbase操作后数据集的缓存策略
spark.fire.hbase.storage.level          =       memory_and_disk_ser
# 通过HBase scan后repartition的分区数，需根据scan后的数据量做配置
spark.fire.hbase.scan.repartitions      =       1200
# fire框架针对jdbc操作后数据集的缓存策略
spark.fire.jdbc.storage.level           =       memory_and_disk_ser
# 通过JdbcOper查询后将数据集放到多少个分区中，需根据实际的结果集做配置
spark.fire.jdbc.query.partitions        =       10
# 是否启用定时调度
spark.fire.task.schedule.enable         =       true
# fire框架rest接口服务最大线程数
spark.fire.restful.max.thread           =       8
# quartz最大线程池大小
spark.fire.quartz.max.thread            =       8

# ----------------------------------------------- < spark 配置 > ----------------------------------------------- #
# spark的应用名称，为空则取类名
spark.appName                           =

spark.chkpoint.dir                      =       hdfs://appcluster/user/spark/ckpoint/

spark.streaming.batch.duration          =
# kafka的groupid，为空则取类名
spark.kafka.group.id                    =
# bigdata表示连接大数据的kafka，zms表示连接zms的kafka集群
spark.kafka.brokers.name                =       bigdata
spark.kafka.topics                      =
# 用于配置启动时的消费位点，默认取最新
spark.kafka.starting.offsets            =       latest

# 数据丢失时执行失败
spark.kafka.failOnDataLoss              =       true
spark.kafka.enable.auto.commit          =       false

spark.log.level                         =       WARN
# fire收集日志保留的最多记录数
spark.fire.acc.log.min.size             =       500
# fire收集日志保留的最少记录数
spark.fire.acc.log.max.size             =       1000
# timer累加器保留最大的记录数
spark.fire.acc.timer.max.size           =       1000
# timer累加器清理几小时之前的记录
spark.fire.acc.timer.max.hour           =       12
# env累加器开关
spark.fire.acc.env.enable               =       true
# env累加器保留最多的记录数
spark.fire.acc.env.max.size             =       500
# env累加器保留最少的记录数
spark.fire.acc.env.min.size             =       100

# ----------------------------------------------- < HDFS 配置 > ----------------------------------------------- #
# 用于是否启用HDFS HA
spark.hdfs.ha.enable                    =       true

# ----------------------------------------------- < hive 配置 > ----------------------------------------------- #
# hive 集群名称（batch离线hive/streaming 180集群hive/test本地测试hive），用于spark跨集群读取hive元数据信息
spark.hive.cluster                      =       batch
spark.default.database.name             =       tmp
spark.default.table.partition.name      =       ds

# ----------------------------------------------- < hbase配置 > ----------------------------------------------- #
# 用于区分不同的hbase集群: batch/streaming/old
spark.hbase.cluster                     =       batch
spark.hbase.batch.size                  =       10000

# ---------------------------------------------- < impala 配置 > ---------------------------------------------- #
spark.impala.connection.url             =      jdbc:hive2://192.168.25.37:21050/;auth=noSasl
spark.impala.jdbc.driver.class.name     =      org.apache.hive.jdbc.HiveDriver

# ----------------------------------------------- < spark参数 > ----------------------------------------------- #
spark.streaming.backpressure.enabled    =      true